# Generated by Django 2.2 on 2020-10-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unit_price',
            field=models.FloatField(default=0.01),
        ),
    ]
