# Generated by Django 2.2 on 2020-09-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
    ]
