# Generated by Django 2.2 on 2020-09-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200918_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='owner',
            new_name='user',
        ),
    ]
