# Generated by Django 2.2 on 2020-09-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_budget_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_timestamp']},
        ),
    ]
